/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed-variant": "#004881",
          "surface": "#f9f9ff",
          "secondary": "#515f74",
          "on-tertiary-container": "#cdd0d1",
          "on-surface-variant": "#414750",
          "surface-container-highest": "#d8e3fb",
          "primary": "#004277",
          "surface-tint": "#1260a5",
          "on-secondary-container": "#57657a",
          "tertiary": "#3e4243",
          "surface-variant": "#d8e3fb",
          "on-primary-fixed": "#001c38",
          "outline-variant": "#c1c7d2",
          "on-primary": "#ffffff",
          "on-background": "#111c2d",
          "on-error-container": "#93000a",
          "on-tertiary-fixed": "#191c1e",
          "on-primary-container": "#b1d1ff",
          "inverse-surface": "#263143",
          "primary-fixed": "#d3e4ff",
          "secondary-fixed-dim": "#b9c7df",
          "primary-fixed-dim": "#a2c9ff",
          "inverse-on-surface": "#ecf1ff",
          "primary-container": "#005a9e",
          "on-secondary-fixed": "#0d1c2e",
          "error-container": "#ffdad6",
          "on-secondary-fixed-variant": "#3a485b",
          "tertiary-fixed-dim": "#c4c7c9",
          "surface-container-low": "#f0f3ff",
          "surface-container": "#e7eeff",
          "surface-container-lowest": "#ffffff",
          "surface-container-high": "#dee8ff",
          "error": "#ba1a1a",
          "on-tertiary-fixed-variant": "#444749",
          "on-surface": "#111c2d",
          "on-secondary": "#ffffff",
          "background": "#f9f9ff",
          "on-tertiary": "#ffffff",
          "on-error": "#ffffff",
          "outline": "#727782",
          "inverse-primary": "#a2c9ff",
          "secondary-fixed": "#d5e3fc",
          "tertiary-fixed": "#e0e3e5",
          "secondary-container": "#d5e3fc",
          "surface-dim": "#cfdaf2",
          "tertiary-container": "#56595b",
          "surface-bright": "#f9f9ff"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "section-gap": "32px",
          "container-padding": "24px",
          "base": "8px",
          "gutter": "16px",
          "element-gap": "12px",
          "sidebar-width": "260px"
      },
      "fontFamily": {
          "body-md": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "headline-xl": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
          "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
          "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
